server:
  port: 5001

spring:
  profiles:
    active: prod
  mvc:
    async:
      request-timeout: 1500


#日志
logging:
  level:
    com.discipline.iquiz.mapper: debug


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




