server:
  port: 5001
  #kurento配置
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: kurento
#    key-store-type: JKS
#    key-alias: kurento-selfsigned

#kurento流媒体服务器地址
#kms:
#  url: ws://8.210.32.42:8888/kurento

spring:
  profiles:
    active: prod
  mvc:
    async:
      request-timeout: 1500

#日志
#logging:
#  level:
#    com.discipline.iquiz.mapper: debug



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




